// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID       int64     `json:"id"`
	Owner    string    `json:"owner"`
	Currency string    `json:"currency"`
	Balance  int64     `json:"balance"`
	CreateAt time.Time `json:"create_at"`
}

type Entries struct {
	ID        int64         `json:"id"`
	AccountID sql.NullInt64 `json:"account_id"`
	// Can be positive or negative!
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// Should only be positive!
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
